### ISSUE TITLE
Create import script

### ISSUE THREAD

**Issue by kenk2** [kenk2/next-config#2]
# Motivation
Now that we have the basic project configuration setup complete, we would like to add scripts to be able to be able to seamlessly initiate this template on any project that I would be doing in the future.

# Tasks
- [x] Create shell scripts to be able to clone this project from the CLI.
- [x] Create shell scripts to add these commands to my bash profile with an alias.
- [x] Test running the commands and verify that they work.
